apiVersion: apps/v1 
kind: Deployment
metadata: 
  name: webapp
spec:
  selector:
    matchLabels:
      app: webapp
  replicas: {{ .Values.webapp.numberReplicas }}
  template:
      metadata:
        labels: 
          app: webapp
      spec:
        containers:
{{- include "template" . | indent 11 }}

---
apiVersion: v1
kind: Service
metadata:
  name: fleetman-webapp
spec:
  type: NodePort
  selector:
    app: webapp
  ports:
    - name: http
      port: 80
      nodePort: 30080

